package sources

var Companies = []string{
	"S&P Global",
	"EnLink Midstream",
	"Burlington Stores",
	"Gilead Sciences",
	"Macy's",
	"MGM Resorts International",
	"Arconic",
	"J.B. Hunt Transport Services",
	"Newmont Goldcorp",
	"Oracle",
	"Murphy USA",
	"INTL FCStone",
	"Discovery",
	"Vistra Energy",
	"ADP",
	"GameStop",
	"Westlake Chemical",
	"Dick's Sporting Goods",
	"ON Semiconductor",
	"NVR",
	"DCP Midstream",
	"PNC Financial Services",
	"DuPont de Nemours",
	"EMCOR Group",
	"Expeditors Intl. of Washington",
	"W.W. Grainger",
	"Charles Schwab",
	"Goodyear Tire & Rubber",
	"Navient",
	"TravelCenters of America",
	"Ecolab",
	"WestRock",
	"CHS",
	"Weyerhaeuser",
	"Caesars Entertainment",
	"Regeneron Pharmaceuticals",
	"State Farm Insurance",
	"Anixter International",
	"Fidelity National Financial",
	"AIG",
	"Interpublic Group",
	"Jacobs Engineering Group",
	"Kroger",
	"Capital One Financial",
	"Supervalu",
	"Rockwell Collins",
	"Altria Group",
	"Mastercard",
	"Home Depot",
	"CenterPoint Energy",
	"Johnson & Johnson",
	"C.H. Robinson Worldwide",
	"Mutual of Omaha Insurance",
	"Anthem",
	"Walgreens Boots Alliance",
	"Dominion Energy",
	"Huntsman",
	"Cheniere Energy",
	"Arthur J. Gallagher",
	"Applied Materials",
	"Kinder Morgan",
	"Whirlpool",
	"Dover",
	"Fiserv",
	"Activision Blizzard",
	"Plains GP Holdings",
	"Sempra Energy",
	"Southern",
	"Frontier Communications",
	"Hewlett Packard Enterprise",
	"WESCO International",
	"Advance Auto Parts",
	"Charter Communications",
	"International Paper",
	"Molina Healthcare",
	"CDW",
	"Land O'Lakes",
	"Danaher",
	"Booz Allen Hamilton",
	"NetApp",
	"Massachusetts Mutual Life Insurance",
	"Kraft Heinz",
	"Unum Group",
	"AK Steel Holding",
	"Analog Devices",
	"Tesla",
	"Nvidia",
	"Energy Transfer",
	"General Electric",
	"Baxter International",
	"Ford Motor",
	"Global Partners",
	"State Street Corp.",
	"ConocoPhillips",
	"NRG Energy",
	"Liberty Mutual Insurance Group",
	"O'Reilly Automotive",
	"Boston Scientific",
	"Bed Bath & Beyond",
	"Foot Locker",
	"Leidos Holdings",
	"Quest Diagnostics",
	"HP",
	"Icahn Enterprises",
	"American Tower",
	"Nordstrom",
	"Seaboard",
	"Loews",
	"Penske Automotive Group",
	"Viacom",
	"National Oilwell Varco",
	"Devon Energy",
	"Northwestern Mutual",
	"Realogy Holdings",
	"Las Vegas Sands",
	"Eastman Chemical",
	"Eversource Energy",
	"Spirit AeroSystems Holdings",
	"Rockwell Automation",
	"General Mills",
	"XPO Logistics",
	"Netflix",
	"Philip Morris International",
	"Comcast",
	"Tapestry",
	"Republic Services",
	"Quanta Services",
	"Twenty-First Century Fox",
	"Univar",
	"WellCare Health Plans",
	"FirstEnergy",
	"Celanese",
	"SunTrust Banks",
	"AGCO",
	"Texas Instruments",
	"United Rentals",
	"Group 1 Automotive",
	"Northern Trust",
	"Tenet Healthcare",
	"BB&T Corp.",
	"Auto-Owners Insurance",
	"Deere",
	"Guardian Life Ins. Co. of America",
	"CVS Health",
	"Arrow Electronics",
	"General Dynamics",
	"BorgWarner",
	"Mosaic",
	"eBay",
	"ABM Industries",
	"Dollar Tree",
	"Zoetis",
	"Franklin Resources",
	"Dell Technologies",
	"Cognizant Technology Solutions",
	"Thermo Fisher Scientific",
	"Facebook",
	"Ball",
	"Autoliv",
	"Beacon Roofing Supply",
	"Bank of America",
	"Thor Industries",
	"Amazon.com",
	"Chesapeake Energy",
	"Sysco",
	"Post Holdings",
	"Apache",
	"Rite Aid",
	"American Financial Group",
	"Alliance Data Systems",
	"World Fuel Services",
	"UnitedHealth Group",
	"Calpine",
	"Union Pacific",
	"Ross Stores",
	"Progressive",
	"Zimmer Biomet Holdings",
	"Conagra Brands",
	"Builders FirstSource",
	"Marathon Oil",
	"Tech Data",
	"Microsoft",
	"Occidental Petroleum",
	"Aflac",
	"Polaris Industries",
	"Hershey",
	"Reinsurance Group of America",
	"KeyCorp",
	"Brighthouse Financial",
	"Marathon Petroleum",
	"Assurant",
	"iHeartMedia",
	"Allstate",
	"Pioneer Natural Resources",
	"Graphic Packaging Holding",
	"Yum China Holdings",
	"Cisco Systems",
	"Genuine Parts",
	"Pacific Life",
	"Cigna",
}
